CREATE TABLE IF NOT EXISTS Cars (
	car_id SERIAL PRIMARY KEY,
	mark VARCHAR(100) NOT NULL DEFAULT 'DEFAULT_MARK',
	model VARCHAR(100) NOT NULL DEFAULT 'DEFAULT_MODEL',
	engine_capacity FLOAT NOT NULL DEFAULT 0,
	prod_year VARCHAR(4) NOT NULL DEFAULT '1990'
);